/**
 * Endpoints de la API GIAMMA 360.
 * Todas las rutas son relativas a `VITE_API_BASE_URL`.
 */
export const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    onboarding: "/auth/onboarding",
  },
  leads: {
    base: "/api/leads",
    byId: (id: number | string) => `/api/leads/${id}`,
    search: "/api/leads/search",
    byStatus: (status: string) => `/api/leads/status/${status}`,
    myLeads: "/api/leads/my-leads",
    unassigned: "/api/leads/unassigned",
    assign: (id: number | string, userId: number | string) => `/api/leads/${id}/assign/${userId}`,
    setStatus: (id: number | string) => `/api/leads/${id}/status`,
    statsByStatus: "/api/leads/stats/by-status",
  },
  vehicles: {
    base: "/api/vehicles",
    available: "/api/vehicles/available",
    search: "/api/vehicles/search",
    byId: (id: number | string) => `/api/vehicles/${id}`,
    byVin: (vin: string) => `/api/vehicles/vin/${vin}`,
    status: (id: number | string) => `/api/vehicles/${id}/status`,
    reserve: (id: number | string) => `/api/vehicles/${id}/reserve`,
    sell: (id: number | string) => `/api/vehicles/${id}/sell`,
    release: (id: number | string) => `/api/vehicles/${id}/release`,
    availability: (id: number | string) => `/api/vehicles/${id}/availability`,
    statsByStatus: "/api/vehicles/stats/by-status",
  },
  quotations: {
    base: "/api/quotations",
    byId: (id: number | string) => `/api/quotations/${id}`,
    byLead: (leadId: number | string) => `/api/quotations/lead/${leadId}`,
    byType: (type: string) => `/api/quotations/type/${type}`,
    valid: "/api/quotations/valid",
    send: (id: number | string) => `/api/quotations/${id}/send`,
    statsByType: "/api/quotations/stats/by-type",
  },
  users: {
    base: "/users",
    byId: (id: number | string) => `/users/${id}`,
    me: "/users/me",
  },
  activities: {
    base: "/api/activities",
    byLead: (leadId: number | string) => `/api/activities/lead/${leadId}`,
    timeline: (leadId: number | string) => `/api/activities/lead/${leadId}/timeline`,
    byType: (type: string) => `/api/activities/type/${type}`,
    myActivities: "/api/activities/my-activities",
    stats: "/api/activities/stats",
  },
  testDrives: {
    base: "/api/test-drives",
    byLead: (leadId: number | string) => `/api/test-drives/lead/${leadId}`,
    byVehicle: (vehicleId: number | string) => `/api/test-drives/vehicle/${vehicleId}`,
    calendar: "/api/test-drives/calendar",
    confirm: (id: number | string) => `/api/test-drives/${id}/confirm`,
    complete: (id: number | string) => `/api/test-drives/${id}/complete`,
    cancel: (id: number | string) => `/api/test-drives/${id}/cancel`,
  },
  documents: {
    byLead: (leadId: number | string) => `/api/documents/lead/${leadId}`,
    byLeadType: (leadId: number | string, type: string) => `/api/documents/lead/${leadId}/type/${type}`,
    verified: (leadId: number | string) => `/api/documents/lead/${leadId}/verified`,
    checklist: (leadId: number | string) => `/api/documents/lead/${leadId}/checklist`,
    stats: (leadId: number | string) => `/api/documents/lead/${leadId}/stats`,
    upload: "/api/documents",
    download: (id: number | string) => `/api/documents/${id}/download`,
    verify: (id: number | string) => `/api/documents/${id}/verify`,
    byId: (id: number | string) => `/api/documents/${id}`,
  },
  excel: {
    uploads: "/api/excel/uploads",
    uploadById: (id: number | string) => `/api/excel/uploads/${id}`,
    uploadStatus: (status: string) => `/api/excel/uploads/status/${status}`,
    upload: "/api/excel/upload",
    template: "/api/excel/template",
    process: (id: number | string) => `/api/excel/uploads/${id}/process`,
    complete: (id: number | string) => `/api/excel/uploads/${id}/complete`,
    error: (id: number | string) => `/api/excel/uploads/${id}/error`,
  },
  dashboard: {
    base: "/api/dashboard",
    kpis: "/api/dashboard/kpis",
    pipeline: "/api/dashboard/pipeline",
  },
  copilot: {
    dailySummary: "/api/copilot/daily-summary",
    hotLeads: "/api/copilot/hot-leads",
    abandonedLeads: "/api/copilot/abandoned-leads",
    nextActions: "/api/copilot/next-actions",
    myNextActions: "/api/copilot/my-next-actions",
    ranking: "/api/copilot/ranking",
  },
} as const;
